Repository jeevatkm/ReplyWithHeaderMozilla, pull requests merged in 2024-08, with the labels that each got.

#157 Improve blockquote handling
  background.js
  manifest.json
  modules/accounts.mjs
  modules/compose.mjs
  modules/settings.mjs
  options/options.html
Labels: enhancement

#158 fix: preserve the user selected locale value from the options ui #155
  background.js
  modules/settings.mjs
  options/options.js
Labels: bug

#166 For v3.1.0 release
  README.md
  manifest.json
  modules/compose.mjs
Labels: bug, enhancement

#169 feat: change design from account to identities in the RWH flow #167
  background.js
  images/mail-identities.svg
  images/rwh-features.png
  manifest.json
  modules/accounts.mjs
  modules/compose.mjs
  modules/settings.mjs
  options/options.css
  options/options.html
  options/options.js
Labels: enhancement

#164 Fix spacing and font size of inserted headers
  modules/compose.mjs
Labels: enhancement

#174 fix: cover cases when 'wrote:' keyword not found in plain text reply mode
  modules/compose.mjs
Labels: bug
